server:
  port: 8080

# profile
spring:
  profiles:
    active: local
#  datasource:
##    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://localhost:3306/dena_store_cn
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
# mybaits conf
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.denachina.springmybaitsshardingdemo.po

logging:
  level:
    com:
      denachina:
        springmybaitsshardingdemo:
          dao:  debug
    org:
      springframework: warn
      apache: warn


